### ISSUE TITLE
cmake error - Debian 11

### ISSUE THREAD

**Issue by ogmkp** [cg2121/obs-decklink-output-filter#2]
Hi.

On Debian 11, I'm trying to build in tree of OBS this plugin but cmake gives error:
```
CMake Error at plugins/obs-decklink-output-filter/CMakeLists.txt:62 (add_library):
  Cannot find source file:

    src/plugin-macros.generated.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

Any idea ?
Thanks.

**Comment by cg2121** [comment]
You should not build OBS plugins that are based on the OBS Plugin Template in tree, as they are not designed to do this.
