### ISSUE TITLE
Not active when OBS starts

### ISSUE THREAD

**Issue by pjoneten** [cg2121/obs-decklink-output-filter#7]
Decklink 8K Pro
To enable SDI output at 1080P after startup I have to go into the filter settings and either toggle the resolution or toggle the Decklink port

**Comment by sanbonribbon** [comment]
Decklink Duo 2
I am having the same issue as @pjoneten where I need to go into the filter settings and toggle the eye to refresh the output source every time I hard shutdown my computer. 

I notice that on commit 3b11ac5 - [Add hack to fix output sometimes not starting] this may be something you are addressing- is it possible to get a compiled version of this to test or instructions on how to compile the build?

**Comment by pjoneten** [comment]
I got around this using a hot key script on boot. Couldn't find any other solution. Not to say there isn't one..

**Comment by cg2121** [comment]
Should be fixed with https://github.com/cg2121/obs-decklink-output-filter/commit/e6e32ddfb145c54789756f48d422a3a212a84ac8

**Comment by sanbonribbon** [comment]
Would you be so kind to push a new compiled build with this fix shipped? 
Thank you
